<?php

namespace ContainerA9cMgor;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FHWtKP0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FHWtKP0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FHWtKP0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CrudController::delete' => ['privates', '.service_locator.7_6BgFX', 'get_ServiceLocator_76BgFXService', true],
            'App\\Controller\\CrudController::edit' => ['privates', '.service_locator.7_6BgFX', 'get_ServiceLocator_76BgFXService', true],
            'App\\Controller\\CrudController::index' => ['privates', '.service_locator.owI9.cF', 'get_ServiceLocator_OwI9_CFService', true],
            'App\\Controller\\CrudController::show' => ['privates', '.service_locator.7_6BgFX', 'get_ServiceLocator_76BgFXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CrudController:delete' => ['privates', '.service_locator.7_6BgFX', 'get_ServiceLocator_76BgFXService', true],
            'App\\Controller\\CrudController:edit' => ['privates', '.service_locator.7_6BgFX', 'get_ServiceLocator_76BgFXService', true],
            'App\\Controller\\CrudController:index' => ['privates', '.service_locator.owI9.cF', 'get_ServiceLocator_OwI9_CFService', true],
            'App\\Controller\\CrudController:show' => ['privates', '.service_locator.7_6BgFX', 'get_ServiceLocator_76BgFXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CrudController::delete' => '?',
            'App\\Controller\\CrudController::edit' => '?',
            'App\\Controller\\CrudController::index' => '?',
            'App\\Controller\\CrudController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CrudController:delete' => '?',
            'App\\Controller\\CrudController:edit' => '?',
            'App\\Controller\\CrudController:index' => '?',
            'App\\Controller\\CrudController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
