<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9cMgor\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9cMgor/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA9cMgor.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA9cMgor\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA9cMgor\App_KernelDevDebugContainer([
    'container.build_hash' => 'A9cMgor',
    'container.build_id' => 'c39fc5e7',
    'container.build_time' => 1621298578,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9cMgor');
